version: "3.9"

services:

  backend:

    build:
      context: ./backend

    container_name: flask-backend

    restart: always

    environment:
      APP_ENV: production

    ports:
      - "5000:5000"

    networks:
      - aws-demo


  frontend:

    build:
      context: ./frontend

    container_name: express-frontend

    restart: always

    environment:
      API_URL: http://backend:5000

    depends_on:
      - backend

    ports:
      - "3000:3000"

    networks:
      - aws-demo


  nginx:

    image: nginx:latest

    container_name: nginx-proxy

    depends_on:
      - backend
      - frontend

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - aws-demo


networks:

  aws-demo:
